"""
ClickHouse Cloud vector store for continuity checking.

Provides the same logical interface as ChromaStore but backed by ClickHouse
Cloud using `clickhouse-connect`.  Embeddings are generated by Gemini
text-embedding-004 (768-dim) and similarity search uses cosineDistance.

Tables use ReplacingMergeTree so upserts are natural (latest wins on
the same ORDER BY key).
"""

from __future__ import annotations

import logging
from typing import Optional

import google.genai as genai

from models.script_state import Scene, ScriptState, ContinuityFact

logger = logging.getLogger(__name__)

# ── Gemini embedding dimension ────────────────────────────────────────
EMBEDDING_DIM = 768


class ClickHouseVectorStore:
    """ClickHouse Cloud vector store for continuity RAG."""

    def __init__(
        self,
        host: str,
        port: int,
        user: str,
        password: str,
        database: str,
        embedding_model: str,
    ):
        self.host = host
        self.port = port
        self.user = user
        self.password = password
        self.database = database
        self.embedding_model = embedding_model
        self._client = None

    # ── Connection ────────────────────────────────────────────────────

    def connect(self):
        """Establish a connection to ClickHouse Cloud and create tables."""
        import clickhouse_connect

        self._client = clickhouse_connect.get_client(
            host=self.host,
            port=self.port,
            username=self.user,
            password=self.password,
            database=self.database,
            secure=True,
        )

        self._create_tables()
        logger.info(f"ClickHouse connected: {self.host}:{self.port}/{self.database}")

    def _create_tables(self):
        """Create the scene and fact embedding tables if they don't exist."""
        self._client.command(f"""
            CREATE TABLE IF NOT EXISTS scene_embeddings (
                project_id   String,
                scene_number UInt32,
                slugline     String     DEFAULT '',
                characters   String     DEFAULT '',
                status       String     DEFAULT '',
                location     String     DEFAULT '',
                scene_text   String,
                embedding    Array(Float32),
                updated_at   DateTime   DEFAULT now()
            )
            ENGINE = ReplacingMergeTree(updated_at)
            ORDER BY (project_id, scene_number)
        """)

        self._client.command(f"""
            CREATE TABLE IF NOT EXISTS fact_embeddings (
                project_id       String,
                fact_id          String,
                scene_established UInt32,
                category         String     DEFAULT '',
                characters       String     DEFAULT '',
                description      String,
                embedding        Array(Float32),
                updated_at       DateTime   DEFAULT now()
            )
            ENGINE = ReplacingMergeTree(updated_at)
            ORDER BY (project_id, fact_id)
        """)

        logger.info("ClickHouse tables verified/created.")

    # ── Embedding ─────────────────────────────────────────────────────

    def _generate_embedding(self, text: str) -> list[float]:
        """Generate a 768-dim embedding using Gemini text-embedding-004."""
        if not text or not text.strip():
            return [0.0] * EMBEDDING_DIM

        try:
            import os
            client = genai.Client(
                vertexai=True,
                project=os.environ.get("GOOGLE_CLOUD_PROJECT", ""),
                location=os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1"),
            )
            result = client.models.embed_content(
                model=self.embedding_model,
                contents=text,
            )
            # result.embeddings is a list; take the first one
            if result.embeddings and len(result.embeddings) > 0:
                return list(result.embeddings[0].values)
            return [0.0] * EMBEDDING_DIM
        except Exception as e:
            logger.error(f"Embedding generation failed: {e}")
            return [0.0] * EMBEDDING_DIM

    # ── Scene Indexing ────────────────────────────────────────────────

    def index_scene(self, project_id: str, scene: Scene):
        """Index a scene's text and embedding into ClickHouse."""
        scene_text = scene.to_screenplay_text()
        if not scene_text.strip():
            scene_text = f"Scene {scene.scene_number}: {scene.slugline} - {scene.action_lines}"

        embedding = self._generate_embedding(scene_text)

        self._client.insert(
            "scene_embeddings",
            [[
                project_id,
                scene.scene_number,
                scene.slugline or "",
                ", ".join(scene.characters),
                scene.status.value if hasattr(scene.status, "value") else str(scene.status),
                scene.location or "",
                scene_text,
                embedding,
            ]],
            column_names=[
                "project_id", "scene_number", "slugline", "characters",
                "status", "location", "scene_text", "embedding",
            ],
        )
        logger.debug(f"ClickHouse: indexed scene {scene.scene_number} for project {project_id}")

    def index_continuity_fact(self, project_id: str, fact: ContinuityFact):
        """Index a continuity fact and its embedding into ClickHouse."""
        embedding = self._generate_embedding(fact.description)

        self._client.insert(
            "fact_embeddings",
            [[
                project_id,
                fact.fact_id,
                fact.scene_established,
                fact.category.value if hasattr(fact.category, "value") else str(fact.category),
                ", ".join(fact.characters_involved),
                fact.description,
                embedding,
            ]],
            column_names=[
                "project_id", "fact_id", "scene_established",
                "category", "characters", "description", "embedding",
            ],
        )
        logger.debug(f"ClickHouse: indexed fact {fact.fact_id} for project {project_id}")

    # ── Querying ──────────────────────────────────────────────────────

    def query_relevant_scenes(
        self,
        project_id: str,
        query: str,
        top_k: int = 5,
    ) -> list[dict]:
        """Vector similarity search for relevant prior scenes."""
        query_embedding = self._generate_embedding(query)

        result = self._client.query(
            """
            SELECT
                scene_text,
                scene_number,
                slugline,
                characters,
                cosineDistance(embedding, %(qv)s) AS distance
            FROM scene_embeddings FINAL
            WHERE project_id = %(pid)s
            ORDER BY distance ASC
            LIMIT %(k)s
            """,
            parameters={
                "qv": query_embedding,
                "pid": project_id,
                "k": top_k,
            },
        )

        matches = []
        for row in result.result_rows:
            matches.append({
                "scene_text": row[0],
                "scene_number": row[1],
                "slugline": row[2],
                "characters": row[3],
                "relevance_score": 1 - row[4],  # cosineDistance → similarity
            })
        return matches

    def query_relevant_facts(
        self,
        project_id: str,
        query: str,
        top_k: int = 10,
    ) -> list[dict]:
        """Vector similarity search for relevant continuity facts."""
        query_embedding = self._generate_embedding(query)

        result = self._client.query(
            """
            SELECT
                description,
                fact_id,
                scene_established,
                category,
                characters,
                cosineDistance(embedding, %(qv)s) AS distance
            FROM fact_embeddings FINAL
            WHERE project_id = %(pid)s
            ORDER BY distance ASC
            LIMIT %(k)s
            """,
            parameters={
                "qv": query_embedding,
                "pid": project_id,
                "k": top_k,
            },
        )

        matches = []
        for row in result.result_rows:
            matches.append({
                "fact_description": row[0],
                "fact_id": row[1],
                "scene_established": row[2],
                "category": row[3],
                "characters": row[4],
                "relevance_score": 1 - row[5],
            })
        return matches

    # ── Bulk Operations ───────────────────────────────────────────────

    def reindex_all(self, project_id: str, state: ScriptState):
        """Full re-indexing of all scenes and facts for a project."""
        self._clear_project(project_id)

        for scene in state.scenes:
            self.index_scene(project_id, scene)

        for fact in state.continuity_log:
            self.index_continuity_fact(project_id, fact)

        logger.info(
            f"ClickHouse: re-indexed project {project_id}: "
            f"{len(state.scenes)} scenes, {len(state.continuity_log)} facts"
        )

    def _clear_project(self, project_id: str):
        """Remove all entries for a project from both tables."""
        try:
            self._client.command(
                "ALTER TABLE scene_embeddings DELETE WHERE project_id = %(pid)s",
                parameters={"pid": project_id},
            )
            self._client.command(
                "ALTER TABLE fact_embeddings DELETE WHERE project_id = %(pid)s",
                parameters={"pid": project_id},
            )
        except Exception as e:
            logger.warning(f"ClickHouse: error clearing project {project_id}: {e}")

    # ── Health ────────────────────────────────────────────────────────

    def health_check(self) -> dict:
        """Return connection status info."""
        try:
            result = self._client.query("SELECT 1")
            scenes_count = self._client.query(
                "SELECT count() FROM scene_embeddings"
            ).result_rows[0][0]
            facts_count = self._client.query(
                "SELECT count() FROM fact_embeddings"
            ).result_rows[0][0]
            return {
                "status": "connected",
                "host": self.host,
                "database": self.database,
                "scenes_indexed": scenes_count,
                "facts_indexed": facts_count,
            }
        except Exception as e:
            return {
                "status": "error",
                "host": self.host,
                "error": str(e),
            }


# ── Module-level singleton ────────────────────────────────────────────

_store: ClickHouseVectorStore | None = None


def get_clickhouse_store() -> ClickHouseVectorStore | None:
    """Get or create the singleton ClickHouse store.
    Returns None if ClickHouse is not configured.
    """
    global _store
    if _store is None:
        from config import settings
        if not settings.clickhouse_enabled:
            logger.info("ClickHouse not configured — skipping.")
            return None
        _store = ClickHouseVectorStore(
            host=settings.clickhouse_host,
            port=settings.clickhouse_port,
            user=settings.clickhouse_user,
            password=settings.clickhouse_password,
            database=settings.clickhouse_database,
            embedding_model=settings.gemini_embedding_model,
        )
        _store.connect()
    return _store
